### ISSUE TITLE
Buying product issue 

### ISSUE THREAD

**Issue by Sandeepsan97** [fssa-batch3/santhanam.mariappan__web_project#23]
### Description of issue
Iam able to buy my own product.

### Expected result
I dont need to buy my own prodoct

### Actual result
Iam able to buy my own product

### Steps to reproduce
1. When iam uploaded a product and i went to buy my own product.
2. It is allowing me to buy my own product.
3. 

```
Path:      /pages/categories.html
Browser:   Edge 113.0.1774.35 on Windows 10
Viewport:  1449 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--zan-arts.netlify.app%2Fpages%2Fcategories.html&os=Windows&os_version=10&browser=Edge&browser_version=113.0&resolution=1449x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--zan-arts.netlify.app/pages/categories.html)

**Comment by santhanam13** [comment]
I clear this bug. Please re check

**Comment by Sandeepsan97** [comment]
Now it is working fine
