### ISSUE TITLE
In your arts page it is  showing another product which is not mine 

### ISSUE THREAD

**Issue by Sandeepsan97** [fssa-batch3/santhanam.mariappan__web_project#24]
### Description of issue
When i click the your art it is  showing another product which is not mine 

### Expected result

It should show only my art.
### Actual result
It is showing the art which is not belong to me.

### Steps to reproduce
1. In my profile page when i click the your art it is showing the product which is not belong to me
2. 
3. 

```
Path:      /asset/css/rewardsandarts
Browser:   Edge 113.0.1774.42 on Windows 10
Viewport:  1449 x 860 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--zan-arts.netlify.app%2Fasset%2Fcss%2Frewardsandarts&os=Windows&os_version=10&browser=Edge&browser_version=113.0&resolution=1449x860&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--zan-arts.netlify.app/asset/css/rewardsandarts)

**Comment by santhanam13** [comment]
I clear this bug . Please recheck

**Comment by Sandeepsan97** [comment]
Now it is working fine
